### ISSUE TITLE
Github CI failed to run image after latest update

### ISSUE THREAD

**Issue by MattivdWeem** [hbontempo-br/docker-postgres-hll#18]
Hey! 

Thanks for the docker image, we've been using it quite heavily in our testing pipeline. 

Starting today, we've encountered an issue with the image. It seems that Github CI is having trouble running a container with the image and its default configuration. Specifically, we're using `docker.io/hbontempo/postgres-hll:13-v2.17`, I've included the output from our CI below for reference.

CI output:
```
  docker.io/hbontempo/postgres-hll:13-v2.17
  /usr/bin/docker create --name 9e2659a2fcd14ad29f3fd5d4023e86bd_hbontempopostgreshll13v217_fe0882 --label 94351b --network github_network_0cf73ca5c667446b9ba2b05a14339c22 --network-alias db -p 5432:5432 --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5 -e "POSTGRES_USER=postgres" -e "POSTGRES_PASSWORD=***" -e "POSTGRES_DB=backend_test" -e GITHUB_ACTIONS=true -e CI=true hbontempo/postgres-hll:13-v2.17
  eeaf2f80cb06c7bb376906817b42a078d284e3106ae9409d44527b9834ba1d30
  /usr/bin/docker start eeaf2f80cb06c7bb376906817b42a078d284e3106ae9409d44527b9834ba1d30
  eeaf2f80cb06c7bb376906817b42a078d284e3106ae9409d44527b9834ba1d30
  /usr/bin/docker ps --all --filter id=eeaf2f80cb06c7bb376906817b42a078d284e3106ae9409d44527b9834ba1d30 --filter status=running --no-trunc --format "{{.ID}} {{.Status}}"
  eeaf2f80cb06c7bb376906817b42a078d284e3106ae9409d44527b9834ba1d30 Up Less than a second (health: starting)
  /usr/bin/docker port eeaf2f80cb06c7bb376906817b42a078d284e3106ae9409d44527b9834ba1d30
  5432/tcp -> 0.0.0.0:5432
  5432/tcp -> [::]:5432

Waiting for all services to be ready
Service container db failed.
  /usr/bin/docker logs --details eeaf2f80cb06c7bb376906817b42a078d284e3106ae9409d44527b9834ba1d30
   initdb: error: invalid locale settings; check LANG and LC_* environment variables
   The files belonging to this database system will be owned by user "postgres".
   This user must also own the server process.
```

To ensure that the issue is indeed caused by the latest tag, we switched the version used in our CI to an older hash. This confirmed that the problem is indeed associated with the latest tag:
```
-       image: hbontempo/postgres-hll:13-v2.17
+       image: hbontempo/postgres-hll@sha256:84344a1c31ce998282c8acbcd04ee8a9c2cf3cfe775e359b6e236ffa34f25823
```

**Comment by hbontempo-br** [comment]
Thanks for the report.
I managed to reproduce the problem.
Working on it

**Comment by hbontempo-br** [comment]
@MattivdWeem your pipeline should be working now.
Debian images are working now.
(Still working on the Alpine based ones)

**Comment by MattivdWeem** [comment]
> @MattivdWeem your pipeline should be working now. Debian images are working now. (Still working on the Alpine based ones)

@hbontempo-br thanks for the swift response! we've reverted back to using the `hbontempo/postgres-hll:13-v2.17` tag and i can confirm that it's working as expected.
